defaults: &defaults
  working_directory: /go/src/github.com/gruntwork-io/package-openvpn
  docker:
    - image: 087285199408.dkr.ecr.us-east-1.amazonaws.com/circle-ci-test-image-base:go1.13

version: 2.0
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/gruntwork-io/package-openvpn

      - run:
          command: |
              mkdir -p /tmp/logs
              run-go-tests --path test | tee /tmp/logs/all.log

      - run:
          name: parse test output
          command: terratest_log_parser --testlog /tmp/logs/all.log --outputdir /tmp/logs
          when: always
      - store_artifacts:
          path: /tmp/logs
      - store_test_results:
          path: /tmp/logs


  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/gruntwork-io/package-openvpn
      - run: build-go-binaries --src-path modules/openvpn-admin/src --app-name openvpn-admin --dest-path bin --ld-flags "-X main.VERSION=$CIRCLE_TAG"
      - persist_to_workspace:
          root: .
          paths: bin

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/gruntwork-io/package-openvpn
      - run: upload-github-release-assets bin/*

workflows:
  version: 2
  build-and-test:
    jobs:
      - test:
          requires:
            - install_dependencies
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/

      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/


  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: master
    jobs:
      - install_dependencies
      - test:
          requires:
            - install_dependencies
