defaults: &defaults
  working_directory: /go/src/github.com/gruntwork-io/package-openvpn
  docker:
    - image: 087285199408.dkr.ecr.us-east-1.amazonaws.com/circle-ci-test-image-base:go1.11

version: 2
jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/gruntwork-io/package-openvpn
      - restore_cache:
          keys:
            - dep-{{ checksum "modules/openvpn-admin/Gopkg.lock" }}-{{ checksum "test/Gopkg.lock" }}
      - run: (cd modules/openvpn-admin && dep ensure)
      - run: (cd test && dep ensure)
      - save_cache:
          key: dep-{{ checksum "modules/openvpn-admin/Gopkg.lock" }}-{{ checksum "test/Gopkg.lock" }}
          paths:
            - /go/src/github.com/gruntwork-io/package-openvpn/modules/openvpn-admin/vendor
            - /go/src/github.com/gruntwork-io/package-openvpn/test/vendor
      - persist_to_workspace:
          root: .
          paths:
            - modules/openvpn-admin/vendor
            - test/vendor

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/gruntwork-io/package-openvpn
      - run: build-go-binaries --circle-ci-2 --src-path modules/openvpn-admin/src --app-name openvpn-admin --dest-path examples/bin --os linux --arch amd64 --ld-flags "-X main.VERSION=$CIRCLE_TAG"
      - run: mv examples/bin/openvpn-admin_linux_amd64 examples/bin/openvpn-admin

      - run:
          name: install terraform 0.11
          command: |
            # Since this module hasn't been updated with terraform 0.12 yet, we replace terraform in the image with
            # 0.11.
            wget https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip
            unzip -o terraform_0.11.14_linux_amd64.zip -d ~/terraform
            chmod u+x ~/terraform/terraform*
            mv ~/terraform/terraform /usr/local/bin/terraform

      - run:
          command: |
              mkdir -p /tmp/logs
              run-go-tests --circle-ci-2 --path test | tee /tmp/logs/all.log

      - run:
          name: parse test output
          command: terratest_log_parser --testlog /tmp/logs/all.log --outputdir /tmp/logs
          when: always
      - store_artifacts:
          path: /tmp/logs
      - store_test_results:
          path: /tmp/logs


  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/gruntwork-io/package-openvpn
      - run: build-go-binaries --circle-ci-2 --src-path modules/openvpn-admin/src --app-name openvpn-admin --dest-path bin --ld-flags "-X main.VERSION=$CIRCLE_TAG"
      - persist_to_workspace:
          root: .
          paths: bin

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/gruntwork-io/package-openvpn
      - run: upload-github-release-assets bin/*

workflows:
  version: 2
  build-and-test:
    jobs:
      - install_dependencies:
          filters:
            tags:
              only: /^v.*/
      - test:
          requires:
            - install_dependencies
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/

      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/


  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: master
    jobs:
      - install_dependencies
      - test:
          requires:
            - install_dependencies
