defaults: &defaults
  docker:
    - image: 087285199408.dkr.ecr.us-east-1.amazonaws.com/circle-ci-test-image-base:tf13

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      # Run pre-commit hooks and fail the build if any hook finds required changes.
      - run:
          name: run precommit
          command: |
            # Oct 26, 2019: Install the last known working version of pre-commit. Also, we have to pin the version of
            # transitive dependencies that are being pulled in which released new versions that are no longer compatible
            # with any python < 3.6.
            pip install pre-commit==1.21.0 cfgv==2.0.1 zipp==1.1.0
            pre-commit install
            pre-commit run --all-files

      - run:
          command: |
              mkdir -p /tmp/logs
              run-go-tests --path test | tee /tmp/logs/all.log

      - run:
          name: parse test output
          command: terratest_log_parser --testlog /tmp/logs/all.log --outputdir /tmp/logs
          when: always
      - store_artifacts:
          path: /tmp/logs
      - store_test_results:
          path: /tmp/logs


  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/gruntwork-io/package-openvpn
      - run: build-go-binaries --src-path modules/openvpn-admin/src --app-name openvpn-admin --dest-path bin --ld-flags "-X main.VERSION=$CIRCLE_TAG"
      - persist_to_workspace:
          root: .
          paths: bin

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /go/src/github.com/gruntwork-io/package-openvpn
      - run: |
          cd /go/src/github.com/gruntwork-io/package-openvpn
          upload-github-release-assets bin/*

workflows:
  version: 2
  build-and-test:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/

      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/


  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: master
    jobs:
      - test
